kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitea-1
  labels: 
    app: gitea-1
  name: gitea-1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitea-1
  template:
    metadata:
      labels:
        name: gitea-1
    spec:
      volumes:
        - name: gitea-volume-2
          persistentVolumeClaim:
            claimName: gitea-pvc-2       
      containers:
        - name: gitea-1
          image: gitea/gitea:latest
          volumeMounts:
            - mountPath: "/data"
              name: gitea-volume-2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
    
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-1
spec:
  type: NodePort
  selector:
    name: gitea-1
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007


      
